### Importing numpy library

In [1]:
import numpy as np

#### Creating 1D numpy arrays. Using them to create numpy 2D array.

In [2]:
arr = np.array ([1, 2, 3, 4, 5])
print (arr)
print (arr.data)
print (arr.dtype)
print (arr.shape)
print (type (arr))

print ()

arr2 = np.array ([4, 5, 6, 7, 8])
print (arr2)
print (arr2.data)
print (arr2.dtype)
print (arr2.shape)

print ()

_2DArr = np.array ([arr, arr2])
print (_2DArr)
print (_2DArr.data)
print (_2DArr.dtype)
print (_2DArr.shape)

[1 2 3 4 5]
int32
(5,)
<class 'numpy.ndarray'>

[4 5 6 7 8]
int32
(5,)

[[1 2 3 4 5]
 [4 5 6 7 8]]
int32
(2, 5)


** *Note* **:

Pass lists of arrays to create 2D arrays.

**Incorrect syntax**:

_2DArr = np.array (arr, arr2)

**Correct syntax**:

_2DArr = np.array ([arr, arr2])

#### Creating nD numpy arrays:

*(using arrays created in previous cells)*

In [3]:
_2DArr2 = np.array ([np.arange (0, 20, 4), np.arange(0, 40, 8)])
print (_2DArr2)
print (_2DArr.shape)

print ()

_3DArr = np.array ([_2DArr, _2DArr2])
print (_3DArr)
print (_3DArr.shape)

print ()

_3DArr2 = np.array ([_2DArr2, _2DArr])
print (_3DArr2)
print (_3DArr2.shape)

print ()

_4DArr = np.array ([_3DArr, _3DArr2])
print (_4DArr)
print (_4DArr.shape)

[[ 0  4  8 12 16]
 [ 0  8 16 24 32]]
(2, 5)

[[[ 1  2  3  4  5]
  [ 4  5  6  7  8]]

 [[ 0  4  8 12 16]
  [ 0  8 16 24 32]]]
(2, 2, 5)

[[[ 0  4  8 12 16]
  [ 0  8 16 24 32]]

 [[ 1  2  3  4  5]
  [ 4  5  6  7  8]]]
(2, 2, 5)

[[[[ 1  2  3  4  5]
   [ 4  5  6  7  8]]

  [[ 0  4  8 12 16]
   [ 0  8 16 24 32]]]


 [[[ 0  4  8 12 16]
   [ 0  8 16 24 32]]

  [[ 1  2  3  4  5]
   [ 4  5  6  7  8]]]]
(2, 2, 2, 5)


#### Creating Special numpy arrays using numpy methods...

In [4]:
ones = np.ones ((2, 4, 3), dtype = int)
print (ones)

print ()

zeros = np.zeros ((3, 3), dtype = complex)
print (zeros)

print ()

# not to be confused with random from random module
rand = np.random.random ((3, 4))
print (rand)

print ()

# creates an "empty" array; array initialized to arbitrary values
empty = np.empty ((2, 3))
print (empty)

print ()

full = np.full ((3, 2), 11)
print (full)

print ()

# creates an identity matrix
diagonal = np.eye (5, 3)
print (diagonal)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]

[[0.94702121 0.21976444 0.44711188 0.60189467]
 [0.03392908 0.47485751 0.67549603 0.5890447 ]
 [0.06032561 0.90715582 0.28327427 0.47080314]]

[[5.48477883e+241 2.64521041e+185 1.96086573e+243]
 [5.98129759e-154 3.80985847e+180 6.01334668e-154]]

[[11 11]
 [11 11]
 [11 11]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Typecasting the numpy array to another object type

*(using arrays created in previous cells)*

In [5]:
print (full)
print (full.dtype)

print ()

full = full.astype (float)
print (full)
print (full.dtype)

[[11 11]
 [11 11]
 [11 11]]
int32

[[11. 11.]
 [11. 11.]
 [11. 11.]]
float64


#### Trying Broadcasting

*Rules:*

Operations can be performed when the two arrays are **compatible**. The are compatible when:

1. The dimensions of the arrays are same. Eg. (3, 4) and (3, 4)

2. When any one array has a dimension (1). Eg. (1, 4) (often shown as (4,) when arr.shape is printed)

Broadcasting depends heavily on the fact that the shapes are compatible. If they are not, changes to shape must be made.

In [6]:
x = np.ones ((2, 4), dtype = int)
print (x)
print (x.shape)

print ()

y = np.arange (0, -8, -2)
print (y)
print (y.shape)

print ()

print (x - y)
print ()
print (y - x)

[[1 1 1 1]
 [1 1 1 1]]
(2, 4)

[ 0 -2 -4 -6]
(4,)

[[1 3 5 7]
 [1 3 5 7]]

[[-1 -3 -5 -7]
 [-1 -3 -5 -7]]


In [7]:
# using array y of previous cell
x = np.ones ((3, 3), dtype = int)
print (x)
print (x.shape)
print (y.shape)

# gives ValueError
# print (y - x)
# print (x - y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
(3, 3)
(4,)


In [8]:
# using array y of previous cells
x = np.zeros ((2, 4, 3), dtype = int)
print (x)
print (x.shape)

print ()

y1 = np.arange (3)
print (y1)
print (y1.shape)

print ()

y2 = np.arange (4)
print (y2)
print (y2.shape)

print ()

print (x + y1)
# print (x + y2) gives ValueError

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(2, 4, 3)

[0 1 2]
(3,)

[0 1 2 3]
(4,)

[[[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]


*Note*:

Arrays will not be compatible if the inner most dimension of both arrays are not same, even if the other dimension(s) is (1).

In [9]:
x = np.array ([[1, 2, 3, 4], [2, 4, 6, 8], np.arange(1, 13, 3)])
print (x)

print ()

x += 10
print (x)

print ()

x -= 10
print (x)

print ()

x *= 10
print (x)

print ()

x = x/5 # shorthand for / gives TypeError
print (x)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 1  4  7 10]]

[[11 12 13 14]
 [12 14 16 18]
 [11 14 17 20]]

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 1  4  7 10]]

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 10  40  70 100]]

[[ 2.  4.  6.  8.]
 [ 4.  8. 12. 16.]
 [ 2.  8. 14. 20.]]


In [10]:
a = np.arange (2, 6)
b = np.arange (3, 7)
c = np.array ([a, b, np.arange(1, 5)])
d = np.array ([np.arange (1, 5), b, a])
print (c)
print ()
print (d)

print ()

print (np.add (c, d))
print (c + d)

print ()

print (np.subtract (c, d))
print (c - d)

print ()

print (np.multiply (c, d)) # element multiplication
print (c * d)

print ()

print (np.divide (c, d))
print (c/d)

print ()

print (np.remainder (c, d))
print (c%d)

[[2 3 4 5]
 [3 4 5 6]
 [1 2 3 4]]

[[1 2 3 4]
 [3 4 5 6]
 [2 3 4 5]]

[[ 3  5  7  9]
 [ 6  8 10 12]
 [ 3  5  7  9]]
[[ 3  5  7  9]
 [ 6  8 10 12]
 [ 3  5  7  9]]

[[ 1  1  1  1]
 [ 0  0  0  0]
 [-1 -1 -1 -1]]
[[ 1  1  1  1]
 [ 0  0  0  0]
 [-1 -1 -1 -1]]

[[ 2  6 12 20]
 [ 9 16 25 36]
 [ 2  6 12 20]]
[[ 2  6 12 20]
 [ 9 16 25 36]
 [ 2  6 12 20]]

[[2.         1.5        1.33333333 1.25      ]
 [1.         1.         1.         1.        ]
 [0.5        0.66666667 0.75       0.8       ]]
[[2.         1.5        1.33333333 1.25      ]
 [1.         1.         1.         1.        ]
 [0.5        0.66666667 0.75       0.8       ]]

[[0 1 1 1]
 [0 0 0 0]
 [1 2 3 4]]
[[0 1 1 1]
 [0 0 0 0]
 [1 2 3 4]]


#### Matrix multiplication using np.dot ()

In [11]:
a = np.array ([np.arange (1, 4), np.arange (4, 7)])
b = np.array ([[4], [5], [6]])
print (a, a.shape)
print (b, b.shape)

print (np.dot (a, b)) # columns of a match with rows f b

[[1 2 3]
 [4 5 6]] (2, 3)
[[4]
 [5]
 [6]] (3, 1)
[[32]
 [77]]


#### Subsets Slicing and Indexing

In [12]:
arr = np.array ([np.arange (5), np.arange (5, 10), np.arange (10, 15), np.arange (15, 20)]) * 2
print (arr, arr.shape)

print ()

print (arr[1][1]) # normal indexing for lists, works for arrays as well
print (arr [1, 1]) # indexing for arrays; doesn't work for lists

print ()

print (arr [:, 1:4]) # slicing used in arrays as well
print (arr [1:3, :])
print (arr [:, -1:-3:-1])
print (arr [-1, 1:4])

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]] (4, 5)

12
12

[[ 2  4  6]
 [12 14 16]
 [22 24 26]
 [32 34 36]]
[[10 12 14 16 18]
 [20 22 24 26 28]]
[[ 8  6]
 [18 16]
 [28 26]
 [38 36]]
[32 34 36]


#### Boolean numpy arrays?

Using a Boolean to create an array with dtype = bool.

Then using that bool type array to print certain elements which satisfy the condition.

In [13]:
my_filter = arr%3 == 0
print (my_filter)
print (my_filter.dtype, my_filter.shape)
print (arr[my_filter])

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]
bool (4, 5)
[ 0  6 12 18 24 30 36]


In [14]:
# using arr array of previous cell
# tuples, lists can be used as array indexes; slicing can't be used
index = (3, 4)
print (arr[index])

# new_index = [1:2, 3] # gives SyntaxError
# print (arr[new_index])

38


#### Reshaping numpy arrays

An array with dimension (m, n) can be changed into another dimension (p, q) if m \* n = p \* q

In [15]:
n_arr = np.array ([[np.arange (3), np.arange (3, 6)], [np.arange (13, 16), np.arange (16, 19)]])
print (n_arr, n_arr.shape)
print ()
print (n_arr.reshape (-1), n_arr.reshape(-1).shape) # changed dimensions from (2, 3, 4) to (24, )
print ()
print (n_arr.reshape (1, 12), n_arr.reshape(1, 12).shape)
print ()
print (n_arr.reshape (3, 4), n_arr.reshape(3, 4).shape)
print ()
print (n_arr.reshape (3, 1, 4), n_arr.reshape(3, 1, 4).shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[13 14 15]
  [16 17 18]]] (2, 2, 3)

[ 0  1  2  3  4  5 13 14 15 16 17 18] (12,)

[[ 0  1  2  3  4  5 13 14 15 16 17 18]] (1, 12)

[[ 0  1  2  3]
 [ 4  5 13 14]
 [15 16 17 18]] (3, 4)

[[[ 0  1  2  3]]

 [[ 4  5 13 14]]

 [[15 16 17 18]]] (3, 1, 4)


#### Importing iris dataset from sklearn module to use slicing

In [16]:
from sklearn import datasets
iris_data = datasets.load_iris ()
x = iris_data['data']
x = x [:, -1]
print (x)

[0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.1 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.  1.3 1.4 1.  1.5 1.  1.4 1.3 1.4 1.5 1.  1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.  1.1 1.  1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.  1.9 2.1 2.  2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.  2.  1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.  2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.  2.3 1.8]
