In [1]:
import numpy as np

#### Creating 1D numpy arrays. Using them to create numpy 2D array.

In [39]:
arr = np.array ([1, 2, 3, 4, 5])
print (arr)
print (arr.data)
print (arr.dtype)
print (arr.shape)
print (type (arr))

arr2 = np.array ([4, 5, 6, 7, 8])
print (arr2)
print (arr2.data)
print (arr2.dtype)
print (arr2.shape)

_2DArr = np.array ([arr, arr2])
print (_2DArr)
print (_2DArr.data)
print (_2DArr.dtype)
print (_2DArr.shape)

[1 2 3 4 5]
int32
(5,)
<class 'numpy.ndarray'>
[4 5 6 7 8]
int32
(5,)
[[1 2 3 4 5]
 [4 5 6 7 8]]
int32
(2, 5)


** *Note* **:

Pass lists of arrays to create 2D arrays.

**Incorrect syntax**:

_2DArr = np.array (arr, arr2)

**Correct syntax**:

_2DArr = np.array ([arr, arr2])

#### Creating nD numpy arrays:

*(using arrays created in previous cells)*

In [40]:
_2DArr2 = np.array ([np.arange (0, 20, 4), np.arange(0, 40, 8)])
print (_2DArr2)
print (_2DArr.shape)

_3DArr = np.array ([_2DArr, _2DArr2])
print (_3DArr)
print (_3DArr.shape)

_3DArr2 = np.array ([_2DArr2, _2DArr])
print (_3DArr2)
print (_3DArr2.shape)

_4DArr = np.array ([_3DArr, _3DArr2])
print (_4DArr)
print (_3DArr2.shape)

[[ 0  4  8 12 16]
 [ 0  8 16 24 32]]
(2, 5)
[[[ 1  2  3  4  5]
  [ 4  5  6  7  8]]

 [[ 0  4  8 12 16]
  [ 0  8 16 24 32]]]
(2, 2, 5)
[[[ 0  4  8 12 16]
  [ 0  8 16 24 32]]

 [[ 1  2  3  4  5]
  [ 4  5  6  7  8]]]
(2, 2, 5)
[[[[ 1  2  3  4  5]
   [ 4  5  6  7  8]]

  [[ 0  4  8 12 16]
   [ 0  8 16 24 32]]]


 [[[ 0  4  8 12 16]
   [ 0  8 16 24 32]]

  [[ 1  2  3  4  5]
   [ 4  5  6  7  8]]]]
(2, 2, 5)


#### Creating Special numpy arrays using numpy methods...

In [66]:
ones = np.ones ((2, 4, 5), dtype = int)
print (ones)

zeros = np.zeros ((3, 3), dtype = complex)
print (zeros)

# not to be confused with random from random module
rand = np.random.random ((3, 4))
print (rand)

# creates an "empty" array; array initialized to arbitrary values
empty = np.empty ((2, 3))
print (empty)

full = np.full ((3, 2), 11)
print (full)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
[[0.05379164 0.81291143 0.25237405 0.50646142]
 [0.39173811 0.97259036 0.9851255  0.31914665]
 [0.8813062  0.22163454 0.3003555  0.80366421]]
[[2.72510035e+224 1.76985064e+295 3.42971271e+243]
 [1.39038548e+229 4.73914476e-153 1.80660672e+176]]
[[11 11]
 [11 11]
 [11 11]]


#### Typecasting the numpy array to another object type

*(using arrays created in previous cells)*

In [67]:
print (full)
print (full.dtype)

full = full.astype (float)
print (full)
print (full.dtype)

[[11 11]
 [11 11]
 [11 11]]
int32
[[11. 11.]
 [11. 11.]
 [11. 11.]]
float64


#### Trying Broadcasting

*Rules:*

Operations can be performed when the two arrays are **compatible**. The are compatible when:

1. The dimensions of the arrays are same. Eg. (3, 4) and (3, 4)

2. When any one array has a dimension (1). Eg. (1, 4) or (4, 1)

**Remember to use np.dot(arr, arr2)**