## Numpy

It is another module like matplotlib, csv, math that provides a data strictire that holds some benefits over python lists. (Compact, faster in reading-writing, convinient, efficient)

Numpy = Numeric Python

NumPy is a python library that is the cre library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high performance multidimensional array object that is a powerful data structure for efficient coputation of arrays and matrics. To work with these arrays, we have a huge amount of high level mathematical functions operate on these matrices and arrays.

**What is a Numpy Array?**

NumPy arrays are like Python lists. But they differ in that an array is a grid of values of same type.

Eg
```
[[1 2 3 4]
 [5 6 7 8]]
```

These arrays hold and represent data in a structured array. 

Generally, an array has a few properties:

1. Data - Stores in memory location
2. Datatype - dtype
3. Shape - Number of elements

```
my_array.data
my_array.dtype
my_array.shape
```

We make a numpy array by passing a list as follows:

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
print(a.data)
print(a.dtype)
print(a.shape)
print(type(a))

int32
(3,)
<class 'numpy.ndarray'>


In [7]:
#Higher dimension array (3D)
b = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]], [[5, 6, 7, 8], [5, 6, 7, 8]]])
b

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [5, 6, 7, 8]]])

DataTypes acceptable by numpy array:

1. int64
2. int32
3. float64
4. float32
5. complex
6. bool

We can also generate arrays with certain values using some functions:

```
# Create array of ones
np.ones((3, 4))

# Create an array of zeroes
np.zeros((2, 3, 4), dtype = np.int16)

# Create an array with random values
np.random.random((2, 2))

# Create an empty array
np.empty((3, 2))

# Create a full array of constant value
np.full((2, 2), 7)

# Create an array o evenl spaced values
np.arange(10, 25, 5)
```

In [9]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.zeros((4, 3, 5), dtype = np.int16)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)

In [11]:
np.random.random((2, 2))

array([[0.24861264, 0.43771979],
       [0.85354019, 0.27448175]])

In [19]:
x = np.empty((3, 4))
print(x)

[[1.21847791e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.20160575e-306 1.81453359e-052 4.35521455e-061 6.53172254e-042]
 [1.80234624e+185 1.95284663e+184 3.73546847e-061 6.34760261e-066]]


In [20]:
np.arange(10, 25, 3)

array([10, 13, 16, 19, 22])

In [21]:
x = np.arange(10, 25, 3)
print(x)
x = x.astype(float)
print(x.dtype)
print(x)

[10 13 16 19 22]
float64
[10. 13. 16. 19. 22.]


## Broadcasting

Allows numpy to work with arrays of different sizes for arithmetic operations.

Rules:

Operations can be performed when the two arrays are compatible. The are compatible when

1. The dimensions are same eg. (3, 4) and (3, 4)

2. When any one has a dimension (1).

In [24]:
x = np.ones((4, 3))
print(x)
y = np.arange(1, 4)
z = x - y
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0. -1. -2.]
 [ 0. -1. -2.]
 [ 0. -1. -2.]
 [ 0. -1. -2.]]


In [25]:
z = x*3
print(z)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [26]:
z = x + y
print(z)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Broadcasting depends heavily on the fact that the shapes are compatible. If they are not, changes to shape must be made.

### Array Operations

We can use the simple operators but we have functions too

    np.add()
    np.substract()
    np.multiply()
    np.divide()
    np.remainder()
    
**Mathematical operations**

    np.exp
    np.sin
    np.log
    etc
    
More functions can be found online. Ain't writing that shit here.

### Subsets Slicing and Indexing

In [27]:
y = np.array([[10, 20, 30], [30, 40, 50], [50, 60, 70]])
print(y)

[[10 20 30]
 [30 40 50]
 [50 60 70]]


In [28]:
print(y[1][2])

50


In [30]:
print(y[1, 2])

50


In [31]:
print(y[:, 2])

[30 50 70]


In [32]:
my_filter = y<=40
print(my_filter)
y[my_filter]

[[ True  True  True]
 [ True  True False]
 [False False False]]


array([10, 20, 30, 30, 40])

In [33]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [35]:
y.reshape(1, 9)

array([[10, 20, 30, 30, 40, 50, 50, 60, 70]])

In [37]:
y.reshape(-1) #Returns a 1D numpy array regardless of previous arrays

array([10, 20, 30, 30, 40, 50, 50, 60, 70])

In [38]:
from sklearn import datasets
iris_data = datasets.load_iris()
x = iris_data['data']
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [39]:
x[:, -1]

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])