### Importing NumPy

In [1]:
import numpy as np

## Numpy questions

### Question 1

Creating a null vector of size 10.

In [2]:
null = np.empty ((10))
print (null, null.shape)

[9.45702226e-308 8.90071984e-308 1.22387720e-307 9.79067808e-307
 1.33508251e-307 8.06610070e-308 1.27950065e-307 1.22383391e-307
 1.16824696e-307 0.00000000e+000] (10,)


### Question 2

Creating a null vector of size 10 with 5th value (at index 4) = 1

In [3]:
null = np.empty ((10))
null[4] = 1
print (null, null.shape)

[9.45702226e-308 8.90071984e-308 1.22387720e-307 9.79067808e-307
 1.00000000e+000 8.06610070e-308 1.27950065e-307 1.22383391e-307
 1.16824696e-307 0.00000000e+000] (10,)


### Question 3

Creating a 3x3 matrix with values ranging from 0 to 8.

In [4]:
matrix = np.array ([np.arange (3), np.arange (3, 6), np.arange (6, 9)])
print (matrix, matrix.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


### Question 4

Creating a 3x3x3 array with random values.

In [5]:
randmatrix = np.random.random ((3, 3, 3))
print (randmatrix, randmatrix.shape)

[[[0.89540628 0.19357171 0.1235069 ]
  [0.14007218 0.50546519 0.65901005]
  [0.98617772 0.14848213 0.90340502]]

 [[0.97808522 0.56491791 0.29426088]
  [0.79009268 0.60565427 0.97706924]
  [0.55016954 0.21649753 0.55915213]]

 [[0.96510224 0.81300023 0.0849775 ]
  [0.96878983 0.95751193 0.89775094]
  [0.17258731 0.60667103 0.0230259 ]]] (3, 3, 3)


### Question 5

Doing matrix mutliplication on a 5x3 matrix and a 3x2 matrix.

In [6]:
a = np.array ([np.arange (1, 4), np.arange (2, 5), np.arange (3, 6), np.arange (4, 7), np.arange (5, 8)])
print (a, a.shape)
b = np.array ([np.arange (2), np.arange (2, 4), np.arange (3, 5)])
print (b, b.shape)
c = np.dot (a, b)
print (c, c.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] (5, 3)
[[0 1]
 [2 3]
 [3 4]] (3, 2)
[[13 19]
 [18 27]
 [23 35]
 [28 43]
 [33 51]] (5, 2)


### Question 6

Creating a 5x5 matrix with row values ranging from 0 to 4.

In [7]:
arr = np.array ([np.arange (5), np.arange (5), np.arange (5), np.arange (5), np.arange (5)])
print (arr, arr.shape)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]] (5, 5)


### Question 7

Subtracting the mean of each row of a matrix.

*Question ambiguous.*

In [8]:
a = np.array ([np.arange (1, 4), np.arange (2, 5), np.arange (3, 6), np.arange (4, 7), np.arange (5, 8)])
b = np.array ([np.arange (2), np.arange (2, 4), np.arange (3, 5)])
c = np.dot (a, b)
print (c, c.shape)
row_mean = c.mean (axis = 1)
diff = row_mean[0]
for i in range (1, len (row_mean)):
    diff -= row_mean[i]
print ('Difference of means of the rows of the matrix =',diff)

[[13 19]
 [18 27]
 [23 35]
 [28 43]
 [33 51]] (5, 2)
Difference of means of the rows of the matrix = -113.0


### Question 8

Diagonal of a dot product (using .dot () and .diagonal ())

In [9]:
a = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array ([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
c = np.dot (a, b)
print (c, c.shape)
print (c.diagonal ())

[[ 84  90  96]
 [201 216 231]
 [318 342 366]] (3, 3)
[ 84 216 366]


### Question 9

Finding the most frequent value in an array.

In [10]:
from statistics import mode
b = np.array ([np.arange (2), np.arange (2, 4), np.arange (3, 5)])
print (b, b.shape)
b = b.reshape (-1)
print (b, b.shape)
new_list = []
for i in range (len (b)):
    new_list.append (b[i])
print ('Most frequent value in the array =',mode (new_list))

[[0 1]
 [2 3]
 [3 4]] (3, 2)
[0 1 2 3 3 4] (6,)
Most frequent value in the array = 3


### Quesiton 10

Creating a random vector of size 10 and sorting it (using .random.random () and .sort ())

In [11]:
randvector = np.random.random (10)
print (randvector)
randvector.sort ()
print (randvector)

[0.24152121 0.54005724 0.80563951 0.18761886 0.64239418 0.24942394
 0.68055726 0.39267855 0.16429571 0.45266339]
[0.16429571 0.18761886 0.24152121 0.24942394 0.39267855 0.45266339
 0.54005724 0.64239418 0.68055726 0.80563951]


### Importing Pandas

In [12]:
import pandas as pd

## Pandas questions

### Question 1

Loading chipotle in a DataFrame.

Printing information about the DataFrame chipo using .info ()

In [13]:
file_path = r'..\datasets\chipotle.tsv'
chipo = pd.read_csv (file_path, delimiter = '\t')
print (chipo.info ())
print (chipo.dtypes)
print (type (chipo))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB
None
order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object
<class 'pandas.core.frame.DataFrame'>


### Question 2

In [14]:
chipo.head (10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

### Question 3

Number of columns in the dataset.

In [15]:
print (len (chipo))

4622


### Question 4

Number of columns in the dataset.

In [16]:
print (len (chipo.keys ()))

5


### Question 5

Names of all columns of the dataset.

In [17]:
print (chipo.columns)
# print (chipo.keys ()) can also be used

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')


### Question 6

*Ambiguous question*

In [18]:
# IDK how the dataset is indexed ...

### Question 7

In [19]:
# another way of doing things ...
max_ordered_item = chipo.groupby ('item_name')['quantity'].count ().max ()
print (max_ordered_item)

726


In [20]:
max_ordered_item = max (chipo.groupby ('item_name')['quantity'].count ())
for i in range (len (chipo.groupby ('item_name')['quantity'].count ())):
    if max_ordered_item == chipo.groupby ('item_name')['quantity'].count ()[i]:
        print ('The most ordered item was', chipo['item_name'][i], end = '.')
        break

The most ordered item was Chicken Burrito.

### Question 8

In [21]:
for i in range (len (chipo.groupby ('item_name')['quantity'].count ())):
    if max_ordered_item == chipo.groupby ('item_name')['quantity'].count ()[i]:
        print (chipo['item_name'][i], 'was the most ordered item with', max_ordered_item, 'total orders.')
        break

Chicken Burrito was the most ordered item with 726 total orders.


### Quesition 9

*Question ambiguous.*

In [22]:
# didn't understand the question

### Question 10

Total number of items ordered.

In [23]:
print (sum (chipo['quantity']))

4972


### Question 11

Typecasting item_price to float

``chipo.assign ()`` assigns a new column to the DataFrame.

In [24]:
string = []
for i in range (len (chipo)):
    string.append ((float (chipo['item_price'][i][1:])))

chipo.drop ('item_price', axis = 1, inplace = True)
chipo = chipo.assign (item_price = string)
chipo.head (10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
6                                                NaN        1.69  
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...        9.25  
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...        9.25

### Question 12

Checking object type of 'item_price'.

In [25]:
print (type (chipo['item_price'][0]))

<class 'numpy.float64'>


### Question 13

Amount of revenue for the period in the dataset.

In [26]:
print ('$', chipo['item_price'].sum ())
# print ('$', sum (chipo['item_price']))

$ 34500.16


### Question 14

Amount of different items sold.

In [27]:
print (len (chipo['item_name'].unique ()))

50


### Question 15

Number of orders in the period of the dataset.

In [28]:
print (len (chipo['order_id'].unique ()))

1834


### Question 16

Average amount per order in the dataset.

In [29]:
print (sum (chipo['item_price'])/len (chipo['order_id'].unique ()))

18.811428571428824
